---
- name: install requirements
  become: true
  ansible.builtin.apt:
    name:
      - debhelper
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - pv
      - lzop
      - mbuffer
      - build-essential
    state: present
  when: ansible_facts.os_family == "Debian"

# based on great answer from https://stackoverflow.com/a/66770158/17214978
- name: get latest stable version tag
  ansible.builtin.shell:
    cmd: curl --silent 'https://api.github.com/repos/jimsalterjrs/sanoid/releases/latest' |  grep '"tag_name":' | cut -d'"' -f4
  register: sanoid_latest_release
  changed_when: false
  args:
    warn: false

# recommend in install doc to do it as root
- name: checkout latest release
  become: true
  ansible.builtin.git:
    repo: "https://github.com/jimsalterjrs/sanoid.git"
    dest: "{{ sanoid_dest }}"
    version: "{{ sanoid_latest_release.stdout }}"

- name: symlink packages
  become: true
  ansible.builtin.command: ln -sf packages/debian .
  args:
    chdir: "{{ sanoid_dest }}"
  changed_when: false

- name: build package
  become: true
  ansible.builtin.command: dpkg-buildpackage -uc -us
  args:
    chdir: "{{ sanoid_dest }}"
  changed_when: false

- name: install sanoid
  become: true
  ansible.builtin.shell: apt install ../sanoid_*_all.deb -y
  args:
    chdir: "{{ sanoid_dest }}"
  changed_when: false
